name: 'Validate an open api file github action'
description: 'Github action to validate an open api file'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'book-open'
  color: 'blue'

# Define your inputs here.
inputs:
  filepath:
    description: 'Path of the open api file to validate'
    required: true

runs:
  using: node20
  main: dist/index.js
